-- USAGESTATS.GITHUB_USAGE_RAW definition
CREATE TABLE USAGESTATS.GITHUB_USAGE_RAW 
   (	"LOGID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	DATECAPTURED DATE NOT NULL ENABLE, 
	NAME NVARCHAR2(64) NOT NULL ENABLE, 
	FULL_NAME NVARCHAR2(128) NOT NULL ENABLE, 
	OWNER NVARCHAR2(64) NOT NULL ENABLE, 
	DESCRIPTION NVARCHAR2(256), 
	URL NVARCHAR2(128) NOT NULL ENABLE, 
	CREATED DATE NOT NULL ENABLE, 
	UPDATED DATE, 
	PUSHED DATE, 
	REPOSITORY_SIZE NUMBER(*,0), 
	VISIBILITY NVARCHAR2(24), 
	IS_FORK NUMBER(1,0), 
	IS_ARCHIVED NUMBER(1,0), 
	IS_TEMPLATE NUMBER(1,0), 
	TOPICS_CSV NVARCHAR2(512), 
	EVENTS_COUNT NUMBER(*,0), 
	EVENTS_UNIQUES NUMBER(*,0), 
	EVENTS_COUNT_YESTERDAY NUMBER(*,0), 
	EVENTS_UNIQUES_YESTERDAY NUMBER(*,0), 
	EVENTS_CSV VARCHAR2(4000), 
	PUSHES_COUNT NUMBER(*,0), 
	PUSHES_UNIQUES NUMBER(*,0), 
	PUSHES_COUNT_YESTERDAY NUMBER(*,0), 
	PUSHES_UNIQUES_YESTERDAY NUMBER(*,0), 
	PUSHES_CSV VARCHAR2(4000), 
	PULLS_COUNT NUMBER(*,0), 
	HAS_DISCUSSIONS_ENABLED NUMBER(1,0), 
	HAS_ISSUES_ENABLED NUMBER(1,0), 
	ISSUES_COUNT NUMBER(*,0), 
	ISSUES_OPEN_COUNT NUMBER(*,0), 
	ISSUES_UNIQUES NUMBER(*,0), 
	ISSUES_COUNT_OPENED_YESTERDAY NUMBER(*,0), 
	ISSUES_COUNT_CLOSED_YESTERDAY NUMBER(*,0), 
	ISSUES_UNIQUES_OPENED_YESTERDAY NUMBER(*,0), 
	ISSUES_UNIQUES_CLOSED_YESTERDAY NUMBER(*,0), 
	FORKS_COUNT NUMBER(*,0), 
	FORKS_COUNT_YESTERDAY NUMBER(*,0), 
	FORKS_UNIQUES NUMBER(*,0), 
	FORKS_UNIQUES_YESTERDAY NUMBER(*,0), 
	FORKS_CSV VARCHAR2(4000), 
	STARGAZERS_COUNT NUMBER(*,0), 
	STARGAZERS_CSV VARCHAR2(4000), 
	WATCHERS_COUNT NUMBER(*,0), 
	WATCHERS_CSV VARCHAR2(4000), 
	CONTRIBUTORS_COUNT NUMBER(*,0), 
	CONTRIBUTORS_CSV VARCHAR2(4000), 
	CONTRIBUTIONS_COUNT NUMBER(*,0), 
	CONTRIBUTORS_DETAIL_CSV VARCHAR2(4000), 
	COLLABORATORS_COUNT NUMBER(*,0), 
	COLLABORATORS_CSV VARCHAR2(4000), 
	CLONE_TRAFFIC_COUNT NUMBER(*,0), 
	CLONE_TRAFFIC_COUNT_YESTERDAY NUMBER(*,0), 
	CLONE_TRAFFIC_UNIQUES NUMBER(*,0), 
	CLONE_TRAFFIC_UNIQUES_YESTERDAY NUMBER(*,0), 
	CLONE_TRAFFIC_CSV VARCHAR2(4000), 
	REFERRER_TRAFFIC_COUNT NUMBER(*,0), 
	REFERRER_TRAFFIC_UNIQUES NUMBER(*,0), 
	REFERRER_TRAFFIC_CSV VARCHAR2(4000), 
	PATH_TRAFFIC_COUNT NUMBER(*,0), 
	PATH_TRAFFIC_UNIQUES NUMBER(*,0), 
	PATH_TRAFFIC_CSV VARCHAR2(4000), 
	VIEW_TRAFFIC_COUNT NUMBER(*,0), 
	VIEW_TRAFFIC_COUNT_YESTERDAY NUMBER(*,0), 
	VIEW_TRAFFIC_UNIQUES NUMBER(*,0), 
	VIEW_TRAFFIC_UNIQUES_YESTERDAY NUMBER(*,0), 
	VIEW_TRAFFIC_CSV VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS_PDB" ;
COMMIT;

/* Grant Permissions */
/*
GRANT SELECT ON USAGESTATS.GITHUB_USAGE_RAW TO "USERID";
  GRANT INSERT ON USAGESTATS.GITHUB_USAGE_RAW TO "USERID";
  GRANT UPDATE ON USAGESTATS.GITHUB_USAGE_RAW TO "USERID";
  GRANT DELETE ON USAGESTATS.GITHUB_USAGE_RAW TO "USERID";
  GRANT REFERENCES ON USAGESTATS.GITHUB_USAGE_RAW TO "USERID";
  GRANT SELECT ON USAGESTATS.GITHUB_USAGE_RAW TO "REPORTING_USERID";
  GRANT REFERENCES ON USAGESTATS.GITHUB_USAGE_RAW TO "REPORTING_USERID";
COMMIT;
*/

COMMENT ON TABLE USAGESTATS.GITHUB_USAGE_RAW IS 'Usage statistics from GitHub captured daily, in raw format (from GitHubs API).';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.LOGID IS 'Auto-incremented numeric ID that uniquely identifies each entry.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.DateCaptured IS 'The date and time when the data was downloaded from the API, in UTC.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Name IS 'The name of the code repository.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Full_Name IS 'The full name of the code repository, which includes the name of the organization that owns it.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Owner IS 'The name of the organization that owns the repository.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Description IS 'The public short description of the repository, as shown in GitHub.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.URL IS 'The full HTTPS URL to the repository.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Created IS 'The date and time when the repository was created, in UTC.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Updated IS 'The date and time when the repository was last updated, in UTC.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Pushed IS 'The date and time of the last ''push'' (commit) to the repository, in UTC.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Repository_Size IS 'The current size of the repository, in bytes.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Visibility IS 'Repository visibility type (e.g. Public, Private, Internal).';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Is_Fork IS 'Boolean (1/0) value indicating whether this repository is a fork of another.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Is_Archived IS 'Boolean (1/0) value indicating whether this repository has been archived and is no longer active.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Is_Template IS 'Boolean (1/0) value indicating whether this repository is available to use as a template for future repositories.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Topics_CSV IS 'Topics (tags) for the repository itself (not to be confused with commit or branch tags).';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Events_Count IS 'The total number of events in this repository, including pushes, pulls, following, etc.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Events_Uniques IS 'The total number of unique users who performed an action on this repository, including pushes, pulls, following, etc.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Events_Count_Yesterday IS 'The number of events in this repository, including pushes, pulls, following, etc., that occurred one day before the capture date.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Events_Uniques_Yesterday IS 'The number of unique users who performed an action on this repository, including pushes, pulls, following, etc., on the day before the capture date.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Events_CSV IS 'Comma-separated list of events that occurred one day prior to the capture date. Fields inside each value are separated by pipes. Format: MM/dd/yyyy hh:mm:ss tt|EventType{/Action}|Actor_Login, ...';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Pushes_CSV IS 'Comma-separated list of pushes (commits) that occurred one day prior to the capture date. Fields inside each value are separated by pipes. Format: MM/dd/yyyy hh:mm:ss tt|EventType{/Action}|Actor_Login, ...';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Forks_CSV IS 'Comma-separated list of forks (copies) that occurred one day prior to the capture date. Fields inside each value are separated by pipes. Format: MM/dd/yyyy hh:mm:ss tt|RepositoryName|Owner_Login, ...';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Stargazers_CSV IS 'Comma-separated list of users who have starred (bookmarked) this repository.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Watchers_CSV IS 'Comma-separated list of users who have subscribed to (watching) activity in this repository.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Contributors_CSV IS 'Comma-separated list of users who have contributed to this repository. Note that this field pulls UserName while all others pull Login, but generally both are the same.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Contributors_detail_CSV IS 'Comma-separated list of users who have contributed to this repository and the number of contributions. Format: UserName|0,UserName|0,...';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Collaborators_CSV IS 'Comma-separated list uf users who are interna or external collaborators, meaning their account is setup on this repo with write or admin rights.';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Clone_Traffic_CSV IS 'Comma-separated list of clones (downloads, that is, copies made to local repo with the git clone command) that occurred one day prior to the capture date. Fields inside each value are separated by pipes. Format: MM/dd/yyyy hh:mm:ss tt|Count#|Uniques#, ...';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Referrer_Traffic_CSV IS 'Comma-separated list of referals that occurred one day prior to the capture date. Fields inside each value are separated by pipes. Format: MM/dd/yyyy hh:mm:ss tt|Count#|Uniques#, ...';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.Path_Traffic_CSV IS 'Comma-separated list of URLs visited (that had any views) that occurred in the past 14 days, including the capture date. Only partial URLs are returned (anything after /reponame/), and any blank paths or views of README.md are transformed to read Home (as in home page). Fields inside each value are separated by pipes. Format: PathText|Count#|Uniques#, ...';
COMMENT ON COLUMN USAGESTATS.GITHUB_USAGE_RAW.View_Traffic_CSV IS 'Comma-separated list of views that occurred one day prior to the capture date. Fields inside each value are separated by pipes. Format: MM/dd/yyyy hh:mm:ss tt|Count#|Uniques#, ...';
COMMIT;
